# Generated by Django 3.0.6 on 2020-05-05 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('meeting_room_id', models.CharField(max_length=1000, verbose_name='会議室ID')),
                ('reserver_id', models.CharField(max_length=1000, verbose_name='予約者ID')),
                ('status', models.CharField(max_length=100, verbose_name='ステータス')),
                ('number_of_participants', models.IntegerField(verbose_name='想定人数')),
                ('start_datetime', models.DateTimeField(verbose_name='開始日時')),
                ('end_datetime', models.DateTimeField(verbose_name='終了日時')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reserve',
            },
        ),
    ]
