@startuml

title 会議室予約のドメインモデル

left to right direction


rectangle 予約集約 {
    object "予約\n<集約ルート>" as c1 {
        + 予約ID
        + 会議室ID
        + 延長した回数
        + キャンセル済みかどうか
    }

    object 予約者 {
        + 予約者ID
        + 予約者名
    }

    object 使用人数 {
    }

    object 使用時間帯 {
        - 使用開始日時: 使用日時
        - 使用終了日時: 使用日時
    }
}


rectangle 会議室集約 {
    object 会議室 {
        + 会議室ID
        - 想定使用人数
    }
}


c1 --> 会議室
c1 *-- 予約者
c1 *-- 使用人数
c1 *-- 使用時間帯

' ===== 予約 =====
note left of c1
・ルール3: 15分の延長が最大で2回までできる。
    ・ただし、後ろの予約がある場合は延長できない。
    ・ただし、19:00を過ぎるような延長はできない
end note

note left of c1
・会議室および使用時間帯が重なってしまう場合は、予約ができない
    ・MEMO: 当たり前過ぎると思うけど、それだけ大事なので、書いておく
end note

note left of c1
・ルール4: 1回の予約における使用時間は最大で2時間とする。
    ・ただし、延長時間は含まない(=ガチの最大使用時間は2時間30分)
end note

note left of c1
・想定使用人数を上回る予約も可能とする
    ・動機: 会議室の使用状況を把握する上で大事な情報だから
    ・MEMO: UI上で警告出すくらいでよくね？
end note

' ===== 使用時間帯 =====
note right of 使用時間帯
・ルール1: 使用時間は15分区切りの15分単位とする
    ・分は {00, 15, 30, 45} のいずれかでなければならない
end note

note right of 使用時間帯
・ルール2: 予約できる時間帯は 10:00から19:00 までとする
    ・10:00 <= 開始時刻 < 終了時刻 <= 19:00
end note

note right of 使用時間帯
・ルール3: 1回の予約における使用時間は最大で4時間とする
end note

note right of 使用時間帯
・ルール5: 会議室を予約できるのは、使用したい日の14日前(休日も込み)からとする
    ・時間帯は関係なし
end note





@enduml