@startuml

title 会議室予約ドメインモデル

left to right direction

rectangle 社員集約 {
    object 社員 {
        + 社員ID
        + 社員名
    }
}

rectangle 予約集約 {
    object "予約\n<集約ルート>" as c1 {
        + 予約ID
        + 会議室ID
        + 予約者ID: 社員ID
        + 延長した回数
        + キャンセル済みかどうか
    }

    object 使用人数 {
    }

    object 予約時間帯 {
        - 使用開始日時: 使用日時
        - 使用終了日時: 使用日時
    }


    object 使用日時 {
    }
}


rectangle 会議室集約 {
    object 会議室 {
        + 会議室ID
        - 想定使用人数
    }
}


c1 --> 会議室
c1 --> 社員
c1 *-- 使用人数
c1 *-- 予約時間帯
予約時間帯 "1" *-- "2" 使用日時

' ===== 予約 =====
note left of c1
・ルール3: 15分の延長が最大で2回までできる。
    ・ただし、後ろの予約がある場合は延長できない。
    ・ただし、19:00を過ぎるような延長はできない
    ・
end note

note left of c1
・会議室および予約時間帯が重なってしまう場合は、予約ができない
    ・MEMO: 当たり前過ぎると思うけど、それだけ大事なので、書いておく
end note

note left of c1
・想定使用人数を上回る予約も可能とする
    ・動機: 会議室の使用状況を把握する上で大事な情報だから
    ・MEMO: UI上で警告出すくらいでよくね？
end note



' ===== 予約時間帯 =====
note right of 予約時間帯
・ルール2: 予約できる時間帯は 同日の 10:00から19:00 までとする
    ・10:00 <= 開始時刻 < 終了時刻 <= 19:00
end note


note right of 予約時間帯
・ルール4: 1回の予約における使用時間は最大で2時間とする。
    ・ただし、延長時間は含まない(=ガチの最大使用時間は2時間30分)
end note


' ===== 使用日時 =====
note right of 使用日時
・ルール1: 使用日時は15分区切りの15分単位とする
    ・分は {00, 15, 30, 45} のいずれかでなければならない
end note

note right of 使用日時
使用日時は、過去であってはならない
特に、同日の過去に注意！
end note

note right of 使用日時
・ルール5: 会議室を予約できるのは、申請日を1日目として、15日目までは予約可能とする。土日や祝日は考慮しない。
    ・申請日が 5/1 のときに、 5/15は予約可能、5/16は予約不可。
    ・時間帯は関係なし
end note

note right of 使用人数
1人以上、20人以内
end note

@enduml