@startuml

title 会議室予約ドメインモデル

left to right direction

rectangle 社員集約 {
    object 社員 {
        + 社員ID
        + 社員名
    }
    note top of 社員
    ・社員IDは0埋めの数字3桁である
    end note
}

rectangle 予約集約 {
    object "予約\n<集約ルート>" as c1 {
        + 予約ID
        + 会議室ID
        + 予約者ID: 社員ID
    }

    object 予約ステータス {
        有効
        キャンセル済
    }

    object 使用人数 {
    }

    object 予約時間帯 {
        - 使用開始日時: 使用日時
        - 使用終了日時: 使用日時
    }


    object 使用日時 {
    }
}


rectangle 会議室の使用実績の集約 {
    object "使用実績"  as c2{
        + 使用実績ID
        + 会議室ID
        + 開始時刻
        + 終了時刻
        + 延長した回数

        + 予約ID
    }

    note left of c2
    ・スタートするぜってすると、開始時刻が記録される
    end note

    note left of c2
    ・終了時刻は 初期値は Null なのか？
    ・「解散」する直前で記録される？
    end note

    note left of c2
    ・ルール3: 15分の延長が最大で2回までできる
        ・ただし、後ろの予約がある場合は延長できない
        ・ただし、19:00を過ぎるような延長はできない
    end note

    c2 "1" -right-> "1" c1

}

rectangle 会議室集約 {
    object 会議室 {
        + 会議室ID
        + 会議室名
    }
    note top of 会議室
    ・会議室IDは大文字のアルファベット1文字である
    end note

}


c1 --> 会議室
c1 --> 社員
c1 *-- 使用人数
c1 *-- 予約時間帯
c1 *-- 予約ステータス
予約時間帯 "1" *-- "2" 使用日時


' ===== 予約 =====
note left of c1
・予約ステータスは、予約をしたときには、「有効」となる
end note

note left of c1
・既にキャンセルされている予約を、「有効」にすることはできない
end note


note left of c1
・会議室および予約時間帯が重なってしまう場合は、予約ができない
    ・MEMO: 当たり前過ぎると思うけど、それだけ大事なので、書いておく
end note

note left of c1
・想定使用人数を上回る予約も可能とする
    ・動機: 会議室の使用状況を把握する上で大事な情報だから
    ・MEMO: UI上で警告出すくらいでよくね？
end note



' ===== 予約時間帯 =====
note right of 予約時間帯
・ルール2: 予約できる時間帯は 同日の 10:00から19:00 までとする
    ・10:00 <= 開始時刻 < 終了時刻 <= 19:00
end note


note right of 予約時間帯
・ルール4: 1回の予約における使用時間は最大で2時間とする。
    ・ただし、延長時間は含まない(=ガチの最大使用時間は2時間30分)
end note


' ===== 使用日時 =====
note right of 使用日時
・ルール1: 使用日時は15分区切りの15分単位とする
    ・分は {00, 15, 30, 45} のいずれかでなければならない
end note

note right of 使用日時
使用日時は、過去であってはならない
特に、同日の過去に注意！
end note

note right of 使用日時
・ルール5: 会議室の新規予約や時間帯変更は、その手続きを行う日を1日目として、15日目までは予約可能とする。
    ・時間帯は関係ない。
    ・土日や祝日は考慮しない。
    ・例1: 手続きする日が 4/1 のときに、 4/15は予約可能、4/16は予約不可。
    ・例2: 新規予約した日は 4/1 の場合
        ・新規予約時点では、4/15までが予約可能な範囲である。
        ・ただし、4/10時点で、その予約時間帯を変更する場合は、4/24までが正しい予約可能になる。
end note

note right of 使用人数
1人以上、20人以内
end note

@enduml