@startuml
left to right direction

actor 会議前_予約者 as a1
note right : 変更、キャンセル操作は、予約者本人のみ
actor 会議中_会議参加者  as a3
actor 会議終了後_分析する人 as a2

rectangle {
    a1 --> (会議室を予約する)
    a1 --> (予約済みの会議室をキャンセルする)
    a1 --> (予約済みの会議室を変更する)
    a1 --> (予約済みの会議室の予約時間帯を変更する)
}

rectangle {
    a2 --> (何かの仮説をもって、何かを集計する)
}

rectangle {
    a3 --> (会議室の開始時刻を記録する)
    a3 --> (会議室の終了時刻を記録する)
    a3 --> (会議室の使用終了時刻を延長する)
}

@enduml