@startuml
left to right direction

actor 会議前_予約者 as a1
actor 会議中_会議参加者  as a3
actor 会議終了後_分析する人 as a2


rectangle {
    usecase 会議室を予約する as ReservationUseCase

    agent 会議室名の一覧を取得する機能 as FindAllMeetingRoom #Turquoise
    agent 予約した社員の名前を取得する機能 as FindEmployee #Turquoise
    agent 現在有効な予約をすべて取得する機能 as FindAvailableReservations #Turquoise
    agent 予約できるかを確かめる機能 as ReservationDomainServiceCanNotReserve #Turquoise
    agent 予約した会議室の名前を取得する機能 as FindMeetingRoom #Turquoise

    a1 --> (ReservationUseCase)
    ReservationUseCase ..> FindAllMeetingRoom
    ReservationUseCase ..> FindEmployee
    ReservationUseCase ..> ReservationDomainServiceCanNotReserve
    ReservationUseCase ..> FindMeetingRoom

    usecase 予約内容を変更する as ChangeReservationUseCase
    a1 --> ChangeReservationUseCase
    ChangeReservationUseCase ..> FindAllMeetingRoom
    ChangeReservationUseCase ..> FindEmployee
    ChangeReservationUseCase ..> FindAvailableReservations
    ChangeReservationUseCase ..> ReservationDomainServiceCanNotReserve
    ChangeReservationUseCase ..> FindMeetingRoom


    usecase 予約済みの会議室をキャンセルする as CancelMeetingRoomUsecase
    a1 --> CancelMeetingRoomUsecase
    CancelMeetingRoomUsecase ..>  FindAvailableReservations

    ReservationDomainServiceCanNotReserve ..> FindAvailableReservations
}

rectangle {
    a2 --> (何かの仮説をもって、何かを集計する)
}

rectangle {
    a3 --> (会議室の開始時刻を記録する)
    a3 --> (会議室の終了時刻を記録する)
    a3 --> (会議室の使用終了時刻を延長する)
}

@enduml