@startuml

title 業務フロー図 - 会議室を予約する


|予約者|
partition 会議室を予約 {
  :会議をやることが決まる;
  :会議の参加者を決める;
  :会議の日程を決める;
  :会議室を決める;
  :会議室を予約してみる;
  split
    -> 空いている;
    :予約完了;
  split again
    -> 空いていない;
    :会議室を変更するか、日程調整をする;
    stop
  end split
}


stop

@enduml