
@startuml

title 要求モデル図

left to right direction

actor 経営者
actor 会議室を利用する人
actor 予約する人
actor 施設管理者

note "システム上には現れない、会議室の交換があったりする" as r1
note "会議は中止になったのに会議室予約をキャンセルしないことがよくある" as r2
note "「会議室の予約がとれない」という声が多いが、実際の会議室の利用実績をわからない" as r3
note "会議室の予約が取れない" as r5
note "直前でのキャンセルが多い気がする" as r4
note "コストが無駄にならないよう、できる限り、無駄なく会議室を用意したい" as r6
note "帳簿上に載っていないと、誰が部屋と設備を利用したのかわらかないから、何かあったときに責任の所在がわからなくなる" as r7

:施設管理者: -- r1
:施設管理者: -- r2
:施設管理者: -- r4
:施設管理者: -- r7

:経営者: -- r3
:経営者: -- r6
:経営者: -- r6

:予約する人: -- r5
:会議室を利用する人: -- r5

note as d1 #Turquoise
 予約とキャンセルの予約台帳を作れること
 予約台帳は、集計機能を付けること
end note

note as d2 #Turquoise
 誰が、いつ、何人想定で、どの会議室を予約、キャンセルを
 したか把握できるようにすること
end note

r3 -- d1
r4 -- d1
d1 -- d2


@enduml

集計をしたい
なんとなく、把握したい
それはわかるが、