name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - '**.puml'
#    branches:
#      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: "**.puml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Install java
        run: |
          sudo apt-get install default-jdk && java -version
      - name: Install graphviz
        run: |
          sudo apt-get install graphviz && dot -v
      - name: Install Japanese Language
        run: |
          sudo apt-get install fonts-takao
      - name: Install plantuml
        run: |
          wget 'https://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=http%3A%2F%2Fplantuml.com%2Fstarting&ts=1538667739&use_mirror=jaist' && mv 'plantuml.jar?r=http%3A%2F%2Fplantuml.com%2Fstarting&ts=1538667739&use_mirror=jaist' plantuml.jar
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        run: |
          java -jar plantuml.jar  -v **.puml
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "github-action"
          commit_user_email: "example@email.org"
          commit_author: "github-actions <example@email.org>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
